// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ButtonPrimary: typeof import('./components/shared/ButtonPrimary.vue')['default']
    ButtonSecondary: typeof import('./components/shared/ButtonSecondary.vue')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    Features: typeof import('./components/Features.vue')['default']
    Heading1: typeof import('./components/shared/Heading1.vue')['default']
    Heading2: typeof import('./components/shared/Heading2.vue')['default']
    MdiAlien: typeof import('~icons/mdi/alien')['default']
    MdiArrowRight: typeof import('~icons/mdi/arrow-right')['default']
    MdiGithub: typeof import('~icons/mdi/github')['default']
    MdiMoonWaningCrescent: typeof import('~icons/mdi/moon-waning-crescent')['default']
    MdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
  }
}

export { }
